"""Added timstamps to Item and removed user relation

Revision ID: 05c97ed42ccf
Revises: 60f40b02b769
Create Date: 2026-02-27 18:03:23.881187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c97ed42ccf'
down_revision: Union[str, Sequence[str], None] = '60f40b02b769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('items_owner_id_fkey'), 'items', type_='foreignkey')
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('items_owner_id_fkey'), 'items', 'users', ['owner_id'], ['id'])
    op.drop_column('items', 'updated_at')
    op.drop_column('items', 'created_at')
    # ### end Alembic commands ###
