"""Enhanced Item

Revision ID: 76d88adfeefd
Revises: 9ac86fce9415
Create Date: 2026-03-03 17:51:30.499629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d88adfeefd'
down_revision: Union[str, Sequence[str], None] = '9ac86fce9415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('items', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('items', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=True)
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.alter_column('items', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('items', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
