"""Users Enhanced

Revision ID: 9ac86fce9415
Revises: 05c97ed42ccf
Create Date: 2026-02-27 19:22:51.560105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac86fce9415'
down_revision: Union[str, Sequence[str], None] = '05c97ed42ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('profile_photo', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'profile_photo')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
